name: Generate RSS Feed

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_call:
    inputs:
      container_image:
        description: 'The name of the container image (e.g., dotnet/aspnet)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      container_image:
        description: 'The name of the container image (e.g., dotnet/aspnet)'
        required: true
        type: string

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feed
        run: |
          python mcr_to_rss.py ${{ inputs.container_image }}

      - name: Commit RSS feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.xml
          git commit -m "Update RSS feed for ${{ inputs.container_image }}"
          git push
