name: Generate RSS Feed

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_call:
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    env:
      REPO_LIST: repositories.txt
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feed
        run: |
          python mcr_to_rss.py $REPO_LIST

      - name: Commit RSS feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.xml
          git commit -m "Update RSS feeds"
          git push
